# .github/workflows/ci.yaml

name: Test

on: [push, pull_request]

jobs:
  # ----------------------------------------------------------------------------
  tests:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

        # ----------------------------------------------------------------------
        # Maintain PHP versions here.  Also bump version under `coding-standard`
        # and 'static-analysis' jobs.
        php-versions:
          - '7.4' # Until 28 Nov 2022.
          - '8.0' # Until 26 Nov 2023.
          - '8.1' # Until 25 Nov 2024.
          - '8.2' # Nightly.

        phpunit-versions: ['latest']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          # extensions: mbstring, intl, pdo_sqlite, pdo_mysql
          # coverage: pcov #optional
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
        # composer run-script post-install-cmd --no-interaction
      - name: Test with phpunit
        run: phpunit

  # ----------------------------------------------------------------------------
  coding-standard:
    name: Coding Standard and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # BUMP PHP VERSION HERE ----------------------------------------------
          php-version: '8.1'
          # extensions: mbstring, intl
          tools: phpcs, phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHP CodeSniffer
        run: phpcs

      - name: Code coverage
        run: phpunit -c phpunit.coverage.xml --coverage-text
